version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7-stretch-node-browsers-legacy
    steps:
    - checkout
    - restore_cache:
        key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
    - run:
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - run:
        name: setup Heroku

  deploy:
    working_directory: ~/repo
    docker:
    - image: docker:stable-git
    steps:
    - checkout
    - run:
        command: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
          HEAD:refs/heads/master
workflows:
  version: 2
  build-test-deploy:
    jobs:
    - security-checks
    - build:
        requires:
        - security-checks
    - tests:
        requires:
        - build
    - deploy:
        type: approval
        requires:
        - tests
        filters:
          branches:
            only: master